# Generated by Django 4.2.4 on 2023-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
    ]
